### ISSUE TITLE
Support older ABAP releases

### ISSUE THREAD

**Issue by RainerWinkler** [RainerWinkler/Moose-FAMIX-SAP-Extractor#17]
Provide a script to replace new ABAP statements with old one, so that using the report with ABAP prior 7.40 is easier.

**Comment by ewx** [comment]
Simple Search&Replace won't work due to very complex syntax.

**Comment by RainerWinkler** [comment]
There are still issues to be solved when converting to ABAP 7.31. In the moment the conversion program is at least working.

**Comment by RainerWinkler** [comment]
A first coding to translate to ABAP 7.31 is now included in the master branch
