### ISSUE TITLE
wiki pictures

### ISSUE THREAD

**Issue by larshp** [RainerWinkler/Moose-FAMIX-SAP-Extractor#41]
Hi,
You can consider moving the pictures from https://github.com/RainerWinkler/Moose-FAMIX-SAP-Extractor/tree/master/wiki_pictures to the wiki git repository, as the wiki itself is a git repository:

https://github.com/RainerWinkler/Moose-FAMIX-SAP-Extractor.wiki.git

**Comment by RainerWinkler** [comment]
Folder is moved to the wiki git repository now. Thank you for the tip!
