### ISSUE TITLE
old versions

### ISSUE THREAD

**Issue by larshp** [RainerWinkler/Moose-FAMIX-SAP-Extractor#42]
Hi,
Another idea, the code in https://github.com/RainerWinkler/Moose-FAMIX-SAP-Extractor/tree/master/old%20versions you can move to https://github.com/RainerWinkler/Moose-FAMIX-SAP-Extractor/releases if you like.

That way there will only be 1 version of the code in the git repository, which is the latest.

**Comment by RainerWinkler** [comment]
This is coding that will be replaced. But it is currently still used to generate the actual extraction coding. I only moved it to a package called old_versions.

**Comment by larshp** [comment]
👍

**Comment by RainerWinkler** [comment]
Done at least in parts. The coding for release v0.1.0 is still in the git repository, but the old files are now archived. Thanks for this advice!
