### ISSUE TITLE
Database tables with the same name as a class. ...

### ISSUE THREAD

**Issue by RainerWinkler** [RainerWinkler/Moose-FAMIX-SAP-Extractor#43]
In WBCROSSGT the OTYPE is always TY. Check how to handle this case in the extractor.

**Comment by larshp** [comment]
see https://answers.sap.com/questions/148848/magic-and-a-full-class-table.html

from Horst: "You cannot have dictionary types and classes/interfaces of the same name."

**Comment by RainerWinkler** [comment]
Thank you Lars,
this answers my question :-)
Rainer
