### ISSUE TITLE
errors during activation

### ISSUE THREAD

**Issue by larshp** [RainerWinkler/Moose-FAMIX-SAP-Extractor#59]
Hi,
It looks like there are 2 objects which are missing in the repository?

![image](https://cloud.githubusercontent.com/assets/5888506/26276163/17acfd8c-3d72-11e7-9610-b8efa61a71db.png)

![image](https://cloud.githubusercontent.com/assets/5888506/26276167/1e688ea2-3d72-11e7-9c26-1c544422cabc.png)

**Comment by RainerWinkler** [comment]
Solved.
This error was only seen if the repository is cloned with ABAPGit. The single report to extract data and display multi level usage was not affected.
There where obsolete classes in the repository. I deleted the class to make the demo model, as it is not needed anymore. I only outcommented Z2MSE_PROGRAM_ANALYZER as I wanted to have a look on the coding later (And as I am not yet so used with git, that I really understand, that I can always go back to an earlier version :-) ).
